import {requestUrl} from 'obsidian';
import {Message,Settings,escapeText,messageKey,folderPath} from './core';

export interface AudioRecord{key:string;chat:string;chatName:string;sender:string;timestamp:string;note:string;path:string;status:'downloaded'|'transcribed'|'download_failed'|'transcription_failed';transcript:string;error:string;}
const safe=(value:string)=>escapeText(value).replace(/\n/g,' ');
export function isAudio(message:Message){return message.mediaType==='audio';}
export function audioBase(s:Settings){return `${folderPath(s.folder)}/${s.source}/${folderPath(s.audioFolder)}`;}
export function audioIndexPath(s:Settings){return `${folderPath(s.folder)}/${s.source}/Audio Index.md`;}
export function audioKey(s:Settings,m:Message){return messageKey(s.source,m);}
export function deterministicAudioPath(s:Settings,m:Message,extension:string){
  const ext=/^\.[a-z0-9]{2,5}$/i.test(extension)?extension.toLowerCase():'.bin';
  return `${audioBase(s)}/audio-${audioKey(s,m).slice(0,24)}${ext}`;
}
export function findIndexedAudio(content:string,key:string):string{
  const match=content.match(new RegExp(`<!-- wa-audio-index:${key}:start -->\\n([\\s\\S]*?)\\n<!-- wa-audio-index:${key}:end -->`));
  return match?.[1].match(/^- Audio: \[\[([^\]]+)\]\]$/m)?.[1]??'';
}
export function hasTranscript(content:string,key:string){
  const block=content.match(new RegExp(`<!-- wa-audio-index:${key}:start -->\\n([\\s\\S]*?)\\n<!-- wa-audio-index:${key}:end -->`))?.[1]??'';
  return /- Status: transcribed\s*$/m.test(block);
}
export function indexedTranscript(content:string,key:string):string{
  const block=content.match(new RegExp(`<!-- wa-audio-index:${key}:start -->\\n([\\s\\S]*?)\\n<!-- wa-audio-index:${key}:end -->`))?.[1]??'';
  const value=block.match(/\n### Transcript\n\n([\s\S]*)$/)?.[1]?.trim()??'';
  return value.replace(/\\([\\`*_{}[\]()#!|~])/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
}
export function updateAudioIndex(existing:string,record:AudioRecord):string{
  const title=existing?existing:'# WhatsApp Audio Index\n\nGenerated by WhatsApp Bridge. Entries are keyed by account, conversation and message ID.\n';
  const note=record.note.replace(/\.md$/,'');
  const transcript=record.transcript?`\n### Transcript\n\n${escapeText(record.transcript)}`:'';
  const error=record.error?`\n- Error: ${safe(record.error)}`:'';
  const audio=record.path?`[[${record.path}]]`:'Unavailable';
  const block=`<!-- wa-audio-index:${record.key}:start -->\n## ${record.timestamp.replace('T',' ').replace('.000Z',' UTC')} — ${safe(record.chatName)}\n\n- Conversation: [[${note}|${safe(record.chatName)}]]\n- Chat ID: \`${safe(record.chat)}\`\n- Sender: ${safe(record.sender)}\n- Sent: ${record.timestamp}\n- Audio: ${audio}\n- Status: ${record.status}${error}${transcript}\n<!-- wa-audio-index:${record.key}:end -->`;
  const pattern=new RegExp(`<!-- wa-audio-index:${record.key}:start -->[\\s\\S]*?<!-- wa-audio-index:${record.key}:end -->`);
  return pattern.test(title)?title.replace(pattern,()=>block):`${title.trimEnd()}\n\n${block}\n`;
}
// Read the existing Markdown format as well as newly created indexes. No wacli history query is needed.
export function indexedRecords(content:string):AudioRecord[]{
  const decode=(value:string)=>value.replace(/\\([\\`*_{}[\]()#!|~])/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
  const records:AudioRecord[]=[],seen=new Set<string>();
  for(const match of content.matchAll(/<!-- wa-audio-index:([a-f0-9]{64}):start -->\n([\s\S]*?)\n<!-- wa-audio-index:\1:end -->/g)){
    const [,key,block]=match;
    if(seen.has(key))continue;seen.add(key);
    const conversation=block.match(/^- Conversation: \[\[([^|\]\n]+)\|([^\n]*)\]\]$/m);
    const path=findIndexedAudio(match[0],key),timestamp=block.match(/^- Sent: (.+)$/m)?.[1]??'';
    if(!conversation||!path||!Number.isFinite(Date.parse(timestamp)))continue;
    records.push({key,path,note:conversation[1]+'.md',chatName:decode(conversation[2]),timestamp,
      chat:decode(block.match(/^- Chat ID: `(.*)`$/m)?.[1]??''),sender:decode(block.match(/^- Sender: (.*)$/m)?.[1]??''),
      status:hasTranscript(match[0],key)?'transcribed':'downloaded',transcript:indexedTranscript(match[0],key),error:''});
  }
  return records;
}
export function mergeAudioIntoNote(existing:string,s:Settings,m:Message,path:string,transcript:string):string{
  return mergeAudioByKey(existing,audioKey(s,m),path,transcript);
}
export function mergeAudioByKey(existing:string,key:string,path:string,transcript:string):string{
  if(!/^[a-f0-9]{64}$/.test(key))throw new Error('Invalid audio key.');
  const marker=`<!-- wa-bridge:${key} -->`;
  if(!existing.includes(marker)||!path)return existing;
  const transcriptBlock=transcript?`\n> [!quote] Transcript\n${escapeText(transcript).split('\n').map(line=>`> ${line}`).join('\n')}\n`:'';
  const block=`<!-- wa-audio:${key}:start -->\n![[${path}]]${transcriptBlock}<!-- wa-audio:${key}:end -->`;
  const pattern=new RegExp(`<!-- wa-audio:${key}:start -->[\\s\\S]*?<!-- wa-audio:${key}:end -->`);
  if(pattern.test(existing))return existing.replace(pattern,()=>block);
  const position=existing.indexOf(marker)+marker.length;
  return `${existing.slice(0,position)}\n${block}${existing.slice(position)}`;
}
export async function transcribe(data:ArrayBuffer,filename:string,key:string,model:string,language:string,request:typeof requestUrl=requestUrl):Promise<string>{
  if(!key)throw new Error('Configure an OpenAI API key in Obsidian SecretStorage.');
  const form=new FormData();form.append('file',new Blob([data]),filename);form.append('model',model);
  if(language&&language!=='auto')form.append('language',language);
  // Let the platform encode multipart boundaries and filenames without making a fetch request.
  const encoded=new Response(form);
  const response=await request({url:'https://api.openai.com/v1/audio/transcriptions',method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':encoded.headers.get('Content-Type')!},body:await encoded.arrayBuffer(),throw:false});
  if(response.status<200||response.status>=300)throw new Error(`Transcription service returned HTTP ${response.status}.`);
  const value=response.json as {text?:unknown};
  if(typeof value.text!=='string'||!value.text.trim())throw new Error('Transcription service returned no text.');
  if(value.text.length>2*1024*1024)throw new Error('Transcription response exceeded the safe limit.');
  return value.text.trim();
}
